# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  test.webapp:
    build:
      context: "/Users/kennedysigauke/Work/TestRiderDockerCompose"
      dockerfile: "TestWebApp/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-arm64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "test.webapp:dev"
    ports:
    - "57050:57100"
    - "57250:57300"
    volumes:
    - "/Users/kennedysigauke/Work/TestRiderDockerCompose/TestWebApp:/app:rw"
    - "/Users/kennedysigauke/.local/share/JetBrains/RiderRemoteDebugger/2023.1/LinuxArm64:/riderDebugger"
    - "/Applications/Rider.app/Contents/bin:/riderLogsConf"
    - "/Users/kennedysigauke/Library/Logs/JetBrains/Rider2023.1/DebuggerWorker/JetBrains.Debugger.Worker.2023_5_29_14_56_31:/riderLogs:rw"
    working_dir: "/app"
